ezua:
  domainName: "${DOMAIN_NAME}"
  virtualService:
    endpoint: "catchx.${DOMAIN_NAME}"
    istioGateway: "istio-system/ezaf-gateway"

backend:
  image: erdincka/catchx-backend:latest

frontend:
  image: erdincka/catchx-frontend:latest