ezua:
  domainName: "${DOMAIN_NAME}"
  virtualService:
    endpoint: "catchx.${DOMAIN_NAME}"
    istioGateway: "istio-system/ezaf-gateway"

backend:
  image: ghcr.io/erdincka/catchx-backend:1.0.0

frontend:
  image: ghcr.io/erdincka/catchx-frontend:1.0.0