export interface Endpoints {
  s3_endpoint: string;
  mcp_server_url: string;
}

export interface Credentials {
  cluster_user: string;
  cluster_pass: string;
  /** Generated by the backend, never typed in. */
  s3_access_key: string;
  s3_secret: string;
}

export interface DemoTargets {
  base_volume: string;
  s3_bucket: string;
  stream_path: string;
}

export interface FeatureFlags {
  verify_ssl: boolean;
  mcp_enabled: boolean;
}

export interface Settings {
  cluster_host: string;
  endpoints: Endpoints;
  credentials: Credentials;
  targets: DemoTargets;
  flags: FeatureFlags;
}

export type ServiceStatus = "good" | "degraded" | "failed" | "unknown";

export interface ServiceProbe {
  status: ServiceStatus;
  latency_ms: number;
  detail: string;
  url: string;
}

export type ServiceMatrix = Record<string, ServiceProbe>;

export type ArtefactStatus = "ok" | "missing" | "error" | "unknown";

export interface Readiness {
  client_configured: boolean;
  nfs_mounted: boolean;
  volumes: Record<string, ArtefactStatus>;
  streams: Record<string, ArtefactStatus>;
}

export interface ClusterInfo {
  name: string;
  ip?: string;
  version?: string;
}

/* CatchX needs the cluster REST API and the object store. MCP is optional and
   is only probed when enabled — see backend/settings.py for the rationale. */
export const SERVICE_META: Record<string, { label: string; hint: string; required: boolean }> = {
  cluster: { label: "Data Fabric cluster", hint: ":8443 · REST API", required: true },
  s3:      { label: "S3 object store",     hint: ":9000 · object storage", required: true },
  mcp:     { label: "Data Fabric MCP",     hint: ":5679 · agent tools", required: false },
};

export const SERVICE_ORDER = ["cluster", "s3", "mcp"] as const;
